apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-app
  labels:
    app: aceest-fitness-app
spec:
  type: LoadBalancer
  selector:
    app: aceest-fitness-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
